/////
////  Msg2swift.swift
///   Copyright © 2024 Dmitriy Borovikov. All rights reserved.
//

import Foundation
import ArgumentParser

enum PropertyDeclaration: String, EnumerableFlag {
    case `let`
    case `var`
}

enum ObjectDeclaration: String, EnumerableFlag {
    case `struct`
    case `class`
}

enum DeclarationSuffix: String, EnumerableFlag {
    case codable = "Codable"
    case encodable = "Encodable"
    case decodable = "Decodable"
}

@main
struct Msg2swift: ParsableCommand {
    static var configuration = CommandConfiguration(
        commandName: "msg2swift",
        abstract: "Generate Swift codable models from ROS message files.",
        version: PackageBuild.info.describe)

    @Argument(help: ".msg file(s) to compile.", transform: { URL(fileURLWithPath: $0) })
    var file: [URL]

    @Flag(exclusivity: .exclusive,
          help: ArgumentHelp("Use var or let for object properties."))
    var propertyDeclaration: PropertyDeclaration = .let

    @Flag(exclusivity: .exclusive,
          help: ArgumentHelp("Struct or class declaration."))
    var objectDeclaration: ObjectDeclaration = .struct

    @Flag(exclusivity: .exclusive,
          help: ArgumentHelp("Object declaration suffix."))
    var declarationSuffix: DeclarationSuffix = .codable
    
    @Flag(name: .long,
          inversion: .prefixedNo,
          exclusivity: .chooseLast,
          help: ArgumentHelp(stringLiteral: #"Convert from "snake_case" to "camelCase""#))
    var snakeCase = true
    
    @Flag(name: .shortAndLong, help: "Verbose output")
    var verbose = false
    
    @Option(name: .shortAndLong,
            help: ArgumentHelp("Object name.",
                               discussion: "By default file name used."))
    var name: String?
    
    @Option(name: .shortAndLong,
            help: ArgumentHelp("The output path for generated files.",
                               discussion: "By default generated files written to the current directory.",
                               valueName: "path"))
    var outputDirectory: String?

    mutating func run() throws {
        var generator = SwiftGenerator(propertyDeclaration: propertyDeclaration,
                                       objectDeclaration: objectDeclaration,
                                       declarationSuffix: declarationSuffix,
                                       snakeCase: snakeCase)
        for url in file {
            let messageText = try String(contentsOf: url)
            let name = name ?? url.deletingPathExtension().lastPathComponent
            
            let model = try generator.generateSwiftModel(name: name, messageText: messageText)
            
            let outputDirectory = outputDirectory ?? url.deletingLastPathComponent().path
            let outputURL = URL(fileURLWithPath: outputDirectory).appendingPathComponent(name).appendingPathExtension("swift")
            let header = """
//
// \(name).swift
//
// Generated by msg2swift version \(PackageBuild.info.describe)
//


"""
            do {
                try (header + model).write(to: outputURL, atomically: false, encoding: .utf8)
            } catch  {
                print("Write error \(outputURL.absoluteString) \(error.localizedDescription)", to: &stderror)
                throw ExitCode.failure
            }
            
            if verbose {
                print("Created \(outputURL.path)")
            }
        }
    }
}
